"""
Universal Strategy Translator -- converts a strategy freely between all
four of T58's strategy representations: Manual Strategy Builder config
(T58's internal signal representation; see app/strategy/manual.py's
docstring and app/strategy/base.py's StrategyResult), PineScript v5,
MQL5, and Python (the app's own `generate_signals(df)` convention; see
app/strategy/python.py).

Originally this module only rendered Manual Strategy Builder config ->
PineScript/MQL5 (T58 already parsed PineScript and MQL5 INTO signals for
BACKTESTING via app/strategy/pinescript.py and app/strategy/mql5.py, but
neither of those parsers reduces a hand-written file back into a
structured, re-emittable config -- they evaluate straight into a pandas
signal series and throw the structure away). This module now does both
directions for Pine and MQL5 too: `parse_pinescript`/`parse_mql5` walk
the SAME regex-recognized subset those two backtesting parsers already
support (ta.sma/ema/wma/rsi, ta.crossover/crossunder, iMA/iRSI, C-style
comparisons, strategy.entry/close, trade.Buy/Sell/PositionClose) but
build the structured _Operand/_Condition/_ConditionGroup tree below
instead of evaluating against a DataFrame -- the exact same "fail loudly
on anything unsupported" posture as those two parsers, just symbolic
instead of numeric. `to_python`/`parse_python` add Python as a fifth-ish
target: `to_python` renders a config into a `generate_signals(df)` module
this app's own PythonStrategy adapter can load and backtest directly.

ROUND-TRIP FIDELITY VIA AN EMBEDDED DIRECTIVE: every renderer below
(`to_pinescript`, `to_mql5`, `to_python`) also stamps a single-line
`T58_MANUAL_CONFIG_JSON=<...>` comment near the end of its output --
the exact same "directive comment" idiom app/strategy/pinescript.py and
app/strategy/mql5.py already use for T58_SL_PIPS/T58_SL_ATR_MULT, just
carrying the WHOLE source config instead of one field. Every reverse
parser below (`parse_pinescript`, `parse_mql5`, `parse_python`) looks for
this directive FIRST and, if present, uses it directly instead of
re-deriving a config from the code -- perfectly faithful (recovers
max_bars_in_trade, trailing stop, break-even, and anything else the
code-only symbolic parse below can't reconstruct), and the ONLY way a
Python file can be translated onward at all: arbitrary hand-written
Python (loops, custom indicators, pandas expressions with no fixed
grammar) has no generalizable reduction back to structured conditions,
so `parse_python` raises TranslationError when the directive is absent
rather than guess. Pine and MQL5 files that were never generated by this
tool (hand-written, no directive) still translate via the real symbolic
parse -- see `parse_pinescript`/`parse_mql5` below.

Why this direction, not full bidirectional code-gen: T58 already parses
PineScript and MQL5 INTO signals (app/strategy/pinescript.py,
app/strategy/mql5.py) for backtesting -- that half of the problem is
solved. What was missing is the other direction: a strategy discovered or
optimized inside T58 (the Manual Strategy Builder, Evolution Lab, the
walk-forward-aware GA, Quick Optimize, Iterative Refinement -- every one
of which operates on Manual Strategy Builder config dicts, per
app/optimize/refinement.py and app/optimize/walkforward_ga.py) had no
path to TradingView or a live MT5 account except hand-porting the JSON
logic by eye. This module closes that gap: it walks the SAME
entry_conditions / exit_conditions / risk_management structure
app/strategy/manual.py itself evaluates, and emits equivalent source in
each target language.

Deliberately one-directional and honest about its supported subset (same
philosophy as the Pine/MQL5 *parsers*: fail loudly on anything not
supported rather than silently emit code that looks right and isn't):

  Supported operand kinds: price fields (open/high/low/close), numeric
  constants, sma/ema/wma/rsi/atr, macd/macd_signal/macd_histogram,
  bollinger_mid/upper/lower, highest_high/lowest_low, vwap,
  candle_direction --
  i.e. exactly the indicator kinds app/strategy/indicators.py's
  build_indicator_series() can compute from a single native platform
  function call, so the emitted code isn't secretly re-implementing
  something T58-specific.

  Supported operators: > >= < <= == != and "crosses above"/"crosses
  below" (rendered as ta.crossover/ta.crossunder in Pine -- the SAME
  primitive app/strategy/pinescript.py's own parser recognizes, so a
  translated-then-re-uploaded file still loads; rendered as an explicit
  current-vs-prior-bar comparison in MQL5, since T58's MQL5 parser has no
  crossover primitive to match).

  Supported risk management: fixed-pips or ATR-multiple stop/target
  (rendered as REAL broker-facing exit orders, not just a comment
  directive), max-bars-in-trade, a single daily clock-time exit, and
  long/short/both direction restriction.

  NOT auto-coded (each is instead surfaced as a clearly labeled TODO
  comment naming the exact configured values, non-fatal -- see
  _UNSUPPORTED_RISK_NOTE): trailing stop and break-even. Both require
  stateful, position-lifecycle-aware logic (a mutable stop level that
  moves as the trade develops) that is easy to get subtly wrong, and a
  subtly wrong stop on a live account is exactly the failure mode this
  codebase is built to avoid (see app/strategy/pinescript.py's own
  "fail loudly rather than silently produce an inaccurate ... result"
  principle) -- so these are flagged for the trader to wire up natively
  in their platform's own trailing-stop/break-even mechanism instead of
  guessing at translated stateful code.

  NOT supported at all (raises TranslationError naming the construct,
  before any code is emitted): the Manual Builder's SMC-style/session/
  regime operand kinds (liquidity_sweep, break_of_structure,
  change_of_character, fair_value_gap, order_block, session_high/low,
  previous_day_*, opening_range_*, time_of_day, atr_regime/
  volatility_regime), and expression-string strategies (long_entry="close
  > sma_20") rather than the structured entry_conditions/exit_conditions
  format -- these don't reduce to a single-line indicator comparison a
  retail platform's own native functions can express directly, and a
  hand-port is safer than a confidently-wrong one.

Both outputs also carry the T58_SL_PIPS / T58_SL_ATR_MULT-style directive
comments the Pine/MQL5 *parsers* already recognize (see those modules'
docstrings), so a strategy round-tripped back into T58 later (after any
manual edits made on TradingView/MT5) still has its stop/target settings
recognized automatically.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from typing import Any


class TranslationError(Exception):
    """Raised when a Manual Strategy Builder config uses a construct this
    translator does not know how to safely re-render in the target
    language. Raised BEFORE any output file is produced -- there is no
    such thing as a partially-translated file from this module."""


_PRICE_FIELDS = {"open", "high", "low", "close", "volume"}
_SIMPLE_INDICATOR_KINDS = {"sma", "ema", "wma", "rsi", "atr", "highest_high", "lowest_low", "vwap"}
_MULTI_OUTPUT_KINDS = {"macd", "macd_signal", "macd_histogram", "bollinger_mid", "bollinger_upper", "bollinger_lower"}
_SUPPORTED_INDICATOR_KINDS = _SIMPLE_INDICATOR_KINDS | _MULTI_OUTPUT_KINDS | {"candle_direction"}

_UNSUPPORTED_KIND_HINT = {
    "liquidity_sweep": "structural liquidity-sweep detection",
    "break_of_structure": "market-structure break detection",
    "bos": "market-structure break detection",
    "change_of_character": "structural character-shift detection",
    "choch": "structural character-shift detection",
    "fair_value_gap": "fair-value-gap detection",
    "fvg": "fair-value-gap detection",
    "order_block": "order-block detection",
    "session_high": "session-relative level tracking",
    "session_low": "session-relative level tracking",
    "previous_day_high": "prior-day level tracking",
    "previous_day_low": "prior-day level tracking",
    "previous_day_close": "prior-day level tracking",
    "opening_range_high": "opening-range level tracking",
    "opening_range_low": "opening-range level tracking",
    "time_of_day": "session time-window filtering",
    "atr_regime": "ATR-regime classification",
    "volatility_regime": "volatility-regime classification",
    "swing_high": "confirmed swing-point detection",
    "swing_low": "confirmed swing-point detection",
}


@dataclass(frozen=True)
class _Operand:
    kind: str  # "constant" | "price" | one of _SUPPORTED_INDICATOR_KINDS
    value: float | None = None
    field: str = "close"
    period: int = 14

    def key(self) -> tuple:
        return (self.kind, self.field, self.period)


def _parse_operand(raw: Any, side: str) -> _Operand:
    if isinstance(raw, (int, float)):
        return _Operand(kind="constant", value=float(raw))
    if raw is None:
        raise TranslationError(f"The {side} side of a condition is missing a value.")
    if isinstance(raw, str):
        name = raw.lower().strip()
        if name in _PRICE_FIELDS:
            return _Operand(kind="price", field=name)
        try:
            return _Operand(kind="constant", value=float(raw))
        except ValueError as exc:
            raise TranslationError(f"Unknown {side}-side operand '{raw}'.") from exc
    if not isinstance(raw, dict):
        raise TranslationError(f"Invalid {side}-side operand: {raw!r}")

    kind = str(raw.get("type", raw.get("source", "close"))).lower().strip()
    field_name = str(raw.get("field", "close")).lower().strip()
    try:
        period = max(int(raw.get("period", 14) or 14), 1)
    except (TypeError, ValueError):
        period = 14

    if kind in {"value", "constant", "number"}:
        try:
            return _Operand(kind="constant", value=float(raw.get("value", 0)))
        except (TypeError, ValueError) as exc:
            raise TranslationError("A numeric condition value is required.") from exc
    if kind in {"price", "open", "high", "low", "close", "volume"}:
        col = field_name if kind == "price" else kind
        if col not in _PRICE_FIELDS:
            raise TranslationError(f"Unknown price field '{col}'.")
        return _Operand(kind="price", field=col)
    if kind in _SUPPORTED_INDICATOR_KINDS:
        return _Operand(kind=kind, field=field_name, period=period)

    hint = _UNSUPPORTED_KIND_HINT.get(kind)
    if hint:
        raise TranslationError(
            f"'{kind}' ({hint}) has no direct equivalent as a single native indicator call on a "
            "retail platform -- port this condition by hand rather than risk a silently-wrong "
            "translation. Everything else in this strategy can still be translated separately."
        )
    raise TranslationError(f"Unsupported condition source '{kind}' for translation.")


def _normalize_operator(op: str) -> str:
    op = op.strip().lower()
    if op in {">", "greater than", "gt"}:
        return ">"
    if op in {">=", "greater than or equal", "gte"}:
        return ">="
    if op in {"<", "less than", "lt"}:
        return "<"
    if op in {"<=", "less than or equal", "lte"}:
        return "<="
    if op in {"==", "equal to", "equals", "eq"}:
        return "=="
    if op in {"!=", "not equal", "neq"}:
        return "!="
    if op in {"cross above", "crosses above"}:
        return "crosses_above"
    if op in {"cross below", "crosses below"}:
        return "crosses_below"
    raise TranslationError(f"Unsupported condition operator '{op}' for translation.")


@dataclass(frozen=True)
class _Condition:
    left: _Operand
    operator: str
    right: _Operand


def _parse_condition(raw: dict) -> _Condition:
    if not isinstance(raw, dict):
        raise TranslationError(f"Invalid condition: {raw!r}")
    left = _parse_operand(raw.get("left", raw.get("source", "close")), "left")
    right = _parse_operand(raw.get("right", raw.get("value", 0)), "right")
    operator = _normalize_operator(str(raw.get("operator", ">")))
    return _Condition(left=left, operator=operator, right=right)


@dataclass(frozen=True)
class _ConditionGroup:
    conditions: tuple
    connectors: tuple  # "AND"/"OR" joining conditions[i] and conditions[i+1]


def _parse_group(conditions_raw: list | None, connectors_raw: list | None) -> _ConditionGroup:
    conditions = tuple(_parse_condition(c) for c in (conditions_raw or []))
    connectors = tuple(str(c).upper() for c in (connectors_raw or []))
    return _ConditionGroup(conditions=conditions, connectors=connectors)


@dataclass
class ParsedStrategy:
    name: str
    direction: str  # "long" | "short" | "both"
    long_entry: _ConditionGroup
    short_entry: _ConditionGroup
    long_exit: _ConditionGroup
    short_exit: _ConditionGroup
    max_bars_in_trade: int | None
    time_exit: str | None
    stop_type: str | None      # "fixed" | "atr" | None
    stop_value: float | None
    stop_atr_period: int
    target_type: str | None
    target_value: float | None
    target_atr_period: int
    trailing_enabled: bool
    trailing_value: float | None
    trailing_atr_period: int
    breakeven_enabled: bool
    breakeven_trigger_r: float | None


def parse_manual_config(config: dict) -> ParsedStrategy:
    """Validates and normalizes a Manual Strategy Builder config into the
    structured form the two code generators below both consume. Raises
    TranslationError immediately on anything unsupported -- callers
    should not catch-and-continue partway through, since there is no
    partial output from this module."""
    if not isinstance(config, dict):
        raise TranslationError("Manual strategy configuration must be a dictionary.")
    entries = config.get("entry_conditions")
    if not entries:
        raise TranslationError(
            "Only Manual Strategy Builder configs using the visual-builder 'entry_conditions' format "
            "can be translated -- expression-string strategies (long_entry='close > sma_20') aren't a "
            "structured representation this translator can safely re-render construct-by-construct."
        )
    exits = config.get("exit_conditions", {}) or {}
    rm = config.get("risk_management", {}) or {}

    direction = str(config.get("market", {}).get("direction", config.get("direction", "Both"))).lower()
    if direction not in {"long", "short", "both"}:
        direction = "both"

    time_cfg = rm.get("time_based_exit", {}) or {}
    trailing = rm.get("trailing_stop", {}) or {}
    breakeven = rm.get("break_even", {}) or {}

    max_bars = rm.get("max_bars_in_trade")
    try:
        max_bars = max(int(max_bars), 1) if max_bars else None
    except (TypeError, ValueError):
        max_bars = None

    stop_type = str(rm.get("stop_type", "")).lower() or None
    if stop_type not in {"fixed", "atr"} or rm.get("stop_value") in (None, ""):
        stop_type = None
    target_type = str(rm.get("target_type", "")).lower() or None
    if target_type not in {"fixed", "atr"} or rm.get("target_value") in (None, ""):
        target_type = None

    return ParsedStrategy(
        name=str(config.get("name", "T58 Strategy")).strip() or "T58 Strategy",
        direction=direction,
        long_entry=_parse_group(entries.get("long", []), entries.get("long_connectors")),
        short_entry=_parse_group(entries.get("short", []), entries.get("short_connectors")),
        long_exit=_parse_group(exits.get("long", []), exits.get("long_connectors")),
        short_exit=_parse_group(exits.get("short", []), exits.get("short_connectors")),
        max_bars_in_trade=max_bars,
        time_exit=str(time_cfg["time"]) if time_cfg.get("enabled") and time_cfg.get("time") else None,
        stop_type=stop_type,
        stop_value=float(rm["stop_value"]) if stop_type else None,
        stop_atr_period=max(int(rm.get("stop_atr_period", 14) or 14), 1),
        target_type=target_type,
        target_value=float(rm["target_value"]) if target_type else None,
        target_atr_period=max(int(rm.get("target_atr_period", 14) or 14), 1),
        trailing_enabled=bool(trailing.get("enabled")) and trailing.get("value") not in (None, ""),
        trailing_value=float(trailing["value"]) if trailing.get("value") not in (None, "") else None,
        trailing_atr_period=max(int(trailing.get("atr_period", 14) or 14), 1),
        breakeven_enabled=bool(breakeven.get("enabled")) and breakeven.get("trigger_r") not in (None, ""),
        breakeven_trigger_r=float(breakeven["trigger_r"]) if breakeven.get("trigger_r") not in (None, "") else None,
    )


def _all_operands(parsed: ParsedStrategy):
    for group in (parsed.long_entry, parsed.short_entry, parsed.long_exit, parsed.short_exit):
        for cond in group.conditions:
            yield cond.left
            yield cond.right


def _collect_indicators(parsed: ParsedStrategy) -> dict[tuple, _Operand]:
    seen: dict[tuple, _Operand] = {}
    for op in _all_operands(parsed):
        if op.kind not in ("constant", "price"):
            seen.setdefault(op.key(), op)
    return seen


def _fmt_num(value: float) -> str:
    if float(value).is_integer():
        return str(int(value))
    return f"{value:g}"


def _pine_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _risk_todo_lines(parsed: ParsedStrategy, comment_prefix: str) -> list[str]:
    lines: list[str] = []
    if parsed.trailing_enabled:
        lines.append(
            f"{comment_prefix} TODO(T58): trailing stop not auto-translated -- configure a "
            f"{_fmt_num(parsed.trailing_value)} x ATR({parsed.trailing_atr_period}) trailing stop "
            "natively on this platform."
        )
    if parsed.breakeven_enabled:
        lines.append(
            f"{comment_prefix} TODO(T58): break-even not auto-translated -- move the stop to entry "
            f"once open profit reaches {_fmt_num(parsed.breakeven_trigger_r)}R natively on this platform."
        )
    return lines


# ---------------------------------------------------------------------------
# PineScript v5 generation
# ---------------------------------------------------------------------------

def _pine_source(field_name: str) -> str:
    return field_name if field_name in _PRICE_FIELDS else "close"


def _pine_declare_indicators(indicators: dict[tuple, _Operand]) -> tuple[list[str], dict[tuple, str]]:
    lines: list[str] = []
    var_map: dict[tuple, str] = {}

    macd_fields = sorted({op.field for op in indicators.values() if op.kind in ("macd", "macd_signal", "macd_histogram")})
    for fld in macd_fields:
        src = _pine_source(fld)
        base = f"macd_{fld}"
        lines.append(f"[{base}_line, {base}_signal, {base}_hist] = ta.macd({src}, 12, 26, 9)")
        var_map[("macd", fld, 0)] = f"{base}_line"
        var_map[("macd_signal", fld, 0)] = f"{base}_signal"
        var_map[("macd_histogram", fld, 0)] = f"{base}_hist"

    bb_groups = sorted({(op.field, op.period) for op in indicators.values()
                         if op.kind in ("bollinger_mid", "bollinger_upper", "bollinger_lower")})
    for fld, period in bb_groups:
        src = _pine_source(fld)
        base = f"bb_{fld}_{period}"
        lines.append(f"[{base}_mid, {base}_upper, {base}_lower] = ta.bb({src}, {period}, 2.0)")
        var_map[("bollinger_mid", fld, period)] = f"{base}_mid"
        var_map[("bollinger_upper", fld, period)] = f"{base}_upper"
        var_map[("bollinger_lower", fld, period)] = f"{base}_lower"

    for key, op in indicators.items():
        if op.kind in ("macd", "macd_signal", "macd_histogram", "bollinger_mid", "bollinger_upper", "bollinger_lower"):
            continue
        src = _pine_source(op.field)
        name = f"vwap_{op.field}" if op.kind == "vwap" else f"{op.kind}_{op.period}_{op.field}"
        if op.kind == "sma":
            lines.append(f"{name} = ta.sma({src}, {op.period})")
        elif op.kind == "ema":
            lines.append(f"{name} = ta.ema({src}, {op.period})")
        elif op.kind == "wma":
            lines.append(f"{name} = ta.wma({src}, {op.period})")
        elif op.kind == "rsi":
            lines.append(f"{name} = ta.rsi({src}, {op.period})")
        elif op.kind == "atr":
            lines.append(f"{name} = ta.atr({op.period})")
        elif op.kind == "highest_high":
            lines.append(f"{name} = ta.highest(high, {op.period})")
        elif op.kind == "lowest_low":
            lines.append(f"{name} = ta.lowest(low, {op.period})")
        elif op.kind == "vwap":
            # Session VWAP, matching app.strategy.indicators.vwap()'s own
            # formula exactly: cumulative (H+L+C)/3 * volume, divided by
            # cumulative volume, reset at the start of each new day. Pine's
            # built-in ta.vwap() does the same daily reset by default, so
            # this is a true single-native-call match (not a hand-rolled
            # approximation) -- ignores op.field since VWAP's typical price
            # is always (H+L+C)/3, same as the app's own indicator.
            lines.append(f"{name} = ta.vwap(hlc3)")
        elif op.kind == "candle_direction":
            lines.append(f"{name} = close > open ? 1 : close < open ? -1 : 0")
        else:  # pragma: no cover -- guarded by _SUPPORTED_INDICATOR_KINDS
            raise TranslationError(f"Unhandled indicator kind '{op.kind}' during PineScript generation.")
        var_map[key] = name

    return lines, var_map


def _pine_render_operand(op: _Operand, var_map: dict[tuple, str]) -> str:
    if op.kind == "constant":
        return _fmt_num(op.value)
    if op.kind == "price":
        return _pine_source(op.field)
    return var_map[op.key()]


def _pine_render_condition(cond: _Condition, var_map: dict[tuple, str]) -> str:
    left = _pine_render_operand(cond.left, var_map)
    right = _pine_render_operand(cond.right, var_map)
    if cond.operator == "crosses_above":
        return f"ta.crossover({left}, {right})"
    if cond.operator == "crosses_below":
        return f"ta.crossunder({left}, {right})"
    return f"{left} {cond.operator} {right}"


def _pine_render_group(group: _ConditionGroup, var_map: dict[tuple, str]) -> str:
    if not group.conditions:
        return "false"
    parts = [_pine_render_condition(c, var_map) for c in group.conditions]
    expr = parts[0]
    for i, connector in enumerate(group.connectors):
        if i + 1 < len(parts):
            op = "and" if connector == "AND" else "or"
            # Wrap the whole RUNNING expression once per join (matching
            # _mql5_render_group's style) rather than wrapping each side
            # separately -- the latter puts "and (" / "or (" right before
            # every parenthesized term, and app.strategy.expr.py's
            # function-call guard (`[A-Za-z_]\w*\s*\(`) can't tell that
            # apart from an actual function call, which broke re-parsing
            # this exact output back through T58's own Pine importer.
            expr = f"({expr} {op} {parts[i + 1]})"
    return expr


def to_pinescript(config: dict) -> str:
    """Renders a Manual Strategy Builder config as a standalone PineScript
    v5 strategy() script, ready to paste into TradingView's Pine Editor."""
    parsed = parse_manual_config(config)
    indicators = _collect_indicators(parsed)
    indicator_lines, var_map = _pine_declare_indicators(indicators)

    allow_long = parsed.direction in ("long", "both")
    allow_short = parsed.direction in ("short", "both")

    lines: list[str] = []
    lines.append("//@version=5")
    lines.append(
        f'strategy("{_pine_escape(parsed.name)}", overlay=true, process_orders_on_close=true, '
        "default_qty_type=strategy.percent_of_equity, default_qty_value=100)"
    )
    lines.append("")
    lines.append("// Generated by the T58 Universal Strategy Translator from a Manual Strategy")
    lines.append("// Builder config. Review before trading real or paper capital.")
    if parsed.stop_type == "fixed" or parsed.target_type == "fixed":
        lines.append(
            "// T58_SL_PIPS / T58_TP_PIPS below is expressed in the SAME unit as the Manual"
        )
        lines.append("// Strategy Builder's stop/target values -- set pipSize to match your instrument.")
    lines.append("")
    lines.extend(indicator_lines)
    if indicator_lines:
        lines.append("")

    lines.append(f"longEntryCond = {_pine_render_group(parsed.long_entry if allow_long else _ConditionGroup((), ()), var_map)}")
    lines.append(f"shortEntryCond = {_pine_render_group(parsed.short_entry if allow_short else _ConditionGroup((), ()), var_map)}")
    lines.append(f"longExitCond = {_pine_render_group(parsed.long_exit, var_map)}")
    lines.append(f"shortExitCond = {_pine_render_group(parsed.short_exit, var_map)}")
    lines.append("")

    if parsed.max_bars_in_trade:
        lines.append(f"// T58_MAX_BARS_IN_TRADE={parsed.max_bars_in_trade}")
        lines.append("var int barsInTrade = 0")
        lines.append("barsInTrade := strategy.position_size != 0 ? barsInTrade + 1 : 0")
        lines.append(f"maxBarsExit = barsInTrade >= {parsed.max_bars_in_trade}")
        lines.append("longExitCond := longExitCond or maxBarsExit")
        lines.append("shortExitCond := shortExitCond or maxBarsExit")
        lines.append("")

    if parsed.time_exit:
        try:
            hh, mm = (int(x) for x in parsed.time_exit.split(":")[:2])
        except ValueError:
            raise TranslationError(f"Time-based exit '{parsed.time_exit}' must be in HH:MM format.")
        lines.append(f"// T58_TIME_EXIT={parsed.time_exit}")
        lines.append(f"timeExitCond = (hour > {hh}) or (hour == {hh} and minute >= {mm})")
        lines.append("longExitCond := longExitCond or timeExitCond")
        lines.append("shortExitCond := shortExitCond or timeExitCond")
        lines.append("")

    lines.append("if longEntryCond")
    lines.append('    strategy.entry("Long", strategy.long)')
    lines.append("if shortEntryCond")
    lines.append('    strategy.entry("Short", strategy.short)')
    lines.append('strategy.close("Long", when=longExitCond)')
    lines.append('strategy.close("Short", when=shortExitCond)')
    lines.append("")

    if parsed.stop_type or parsed.target_type:
        lines.append('pipSize = input.float(0.0001, title="Pip Size (match your instrument, e.g. 0.01 for gold)")')
        if parsed.stop_type == "fixed":
            lines.append(f"// T58_SL_PIPS={_fmt_num(parsed.stop_value)}")
            lines.append(f"slDist = {_fmt_num(parsed.stop_value)} * pipSize")
        elif parsed.stop_type == "atr":
            lines.append(f"// T58_SL_ATR_MULT={_fmt_num(parsed.stop_value)}")
            lines.append(f"// T58_ATR_PERIOD={parsed.stop_atr_period}")
            lines.append(f"slAtr = ta.atr({parsed.stop_atr_period})")
            lines.append(f"slDist = slAtr * {_fmt_num(parsed.stop_value)}")
        if parsed.target_type == "fixed":
            lines.append(f"// T58_TP_PIPS={_fmt_num(parsed.target_value)}")
            lines.append(f"tpDist = {_fmt_num(parsed.target_value)} * pipSize")
        elif parsed.target_type == "atr":
            lines.append(f"// T58_TP_ATR_MULT={_fmt_num(parsed.target_value)}")
            lines.append(f"// T58_ATR_PERIOD={parsed.target_atr_period}")
            lines.append(f"tpAtr = ta.atr({parsed.target_atr_period})")
            lines.append(f"tpDist = tpAtr * {_fmt_num(parsed.target_value)}")

        sl_arg = "strategy.position_avg_price - slDist" if parsed.stop_type else "na"
        sl_short_arg = "strategy.position_avg_price + slDist" if parsed.stop_type else "na"
        tp_arg = "strategy.position_avg_price + tpDist" if parsed.target_type else "na"
        tp_short_arg = "strategy.position_avg_price - tpDist" if parsed.target_type else "na"
        lines.append(f'strategy.exit("Long Exit", from_entry="Long", stop={sl_arg}, limit={tp_arg})')
        lines.append(f'strategy.exit("Short Exit", from_entry="Short", stop={sl_short_arg}, limit={tp_short_arg})')
        lines.append("")

    lines.extend(_risk_todo_lines(parsed, "//"))
    lines.extend(_config_directive_lines(config, "//"))
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# MQL5 generation
# ---------------------------------------------------------------------------

_MQL5_KIND_INFO = {
    "sma": ("iMA", "MODE_SMA"), "ema": ("iMA", "MODE_EMA"), "wma": ("iMA", "MODE_LWMA"),
    "rsi": ("iRSI", None), "atr": ("iATR", None),
}


def _mql5_price_call(field_name: str, shift: str) -> str:
    fn = {"open": "iOpen", "high": "iHigh", "low": "iLow", "close": "iClose"}.get(field_name, "iClose")
    return f"{fn}(_Symbol, PERIOD_CURRENT, {shift})"


def _mql5_declare_indicators(indicators: dict[tuple, _Operand]) -> tuple[list[str], list[str], list[str], dict[tuple, str]]:
    """Returns (global declarations, OnInit handle-creation lines,
    OnTick CopyBuffer lines, {operand_key: array_variable_name})."""
    globals_: list[str] = []
    init_lines: list[str] = []
    tick_lines: list[str] = []
    var_map: dict[tuple, str] = {}

    macd_fields = sorted({op.field for op in indicators.values() if op.kind in ("macd", "macd_signal", "macd_histogram")})
    for fld in macd_fields:
        handle = f"h_macd_{fld}"
        globals_.append(f"int {handle};")
        init_lines.append(f'{handle} = iMACD(_Symbol, PERIOD_CURRENT, 12, 26, 9, PRICE_{fld.upper()});')
        for buf_idx, kind in ((0, "macd"), (1, "macd_signal"), (2, "macd_histogram")):
            arr = f"{handle}_buf{buf_idx}"
            globals_.append(f"double {arr}[];")
            tick_lines.append(f"ArraySetAsSeries({arr}, true);")
            tick_lines.append(f"CopyBuffer({handle}, {buf_idx}, 0, 3, {arr});")
            var_map[(kind, fld, 0)] = arr

    bb_groups = sorted({(op.field, op.period) for op in indicators.values()
                         if op.kind in ("bollinger_mid", "bollinger_upper", "bollinger_lower")})
    for fld, period in bb_groups:
        handle = f"h_bb_{fld}_{period}"
        globals_.append(f"int {handle};")
        init_lines.append(f'{handle} = iBands(_Symbol, PERIOD_CURRENT, {period}, 0, 2.0, PRICE_{fld.upper()});')
        for buf_idx, kind in ((0, "bollinger_mid"), (1, "bollinger_upper"), (2, "bollinger_lower")):
            arr = f"{handle}_buf{buf_idx}"
            globals_.append(f"double {arr}[];")
            tick_lines.append(f"ArraySetAsSeries({arr}, true);")
            tick_lines.append(f"CopyBuffer({handle}, {buf_idx}, 0, 3, {arr});")
            var_map[(kind, fld, period)] = arr

    for key, op in indicators.items():
        if op.kind in ("macd", "macd_signal", "macd_histogram", "bollinger_mid", "bollinger_upper", "bollinger_lower"):
            continue
        if op.kind == "candle_direction":
            continue  # rendered inline from price calls, no handle needed
        if op.kind in ("highest_high", "lowest_low"):
            continue  # rendered inline via ArrayMaximum/ArrayMinimum over price calls
        if op.kind == "vwap":
            continue  # rendered inline via the ComputeVWAP() helper (see to_mql5)
        fn, mode = _MQL5_KIND_INFO[op.kind]
        handle = f"h_{op.kind}_{op.period}_{op.field}"
        arr = f"{handle}_buf"
        globals_.append(f"int {handle};")
        globals_.append(f"double {arr}[];")
        if fn == "iMA":
            init_lines.append(f'{handle} = iMA(_Symbol, PERIOD_CURRENT, {op.period}, 0, {mode}, PRICE_{op.field.upper()});')
        elif fn == "iRSI":
            init_lines.append(f'{handle} = iRSI(_Symbol, PERIOD_CURRENT, {op.period}, PRICE_{op.field.upper()});')
        elif fn == "iATR":
            init_lines.append(f'{handle} = iATR(_Symbol, PERIOD_CURRENT, {op.period});')
        tick_lines.append(f"ArraySetAsSeries({arr}, true);")
        tick_lines.append(f"CopyBuffer({handle}, 0, 0, 3, {arr});")
        var_map[key] = arr

    return globals_, init_lines, tick_lines, var_map


def _mql5_render_scalar(op: _Operand, var_map: dict[tuple, str], shift: str = "0") -> str:
    """Renders op's value at `shift` (0 = current/most recent closed bar, 1 = prior)."""
    if op.kind == "constant":
        return _fmt_num(op.value)
    if op.kind == "price":
        return _mql5_price_call(op.field, shift)
    if op.kind == "candle_direction":
        c, o = _mql5_price_call("close", shift), _mql5_price_call("open", shift)
        return f"({c} > {o} ? 1 : ({c} < {o} ? -1 : 0))"
    if op.kind == "highest_high":
        return f"iHigh(_Symbol, PERIOD_CURRENT, iHighest(_Symbol, PERIOD_CURRENT, MODE_HIGH, {op.period}, {shift}))"
    if op.kind == "lowest_low":
        return f"iLow(_Symbol, PERIOD_CURRENT, iLowest(_Symbol, PERIOD_CURRENT, MODE_LOW, {op.period}, {shift}))"
    if op.kind == "vwap":
        return f"ComputeVWAP({shift})"
    return f"{var_map[op.key()]}[{shift}]"


def _mql5_render_condition(cond: _Condition, var_map: dict[tuple, str]) -> str:
    if cond.operator in ("crosses_above", "crosses_below"):
        left0, right0 = _mql5_render_scalar(cond.left, var_map, "0"), _mql5_render_scalar(cond.right, var_map, "0")
        left1, right1 = _mql5_render_scalar(cond.left, var_map, "1"), _mql5_render_scalar(cond.right, var_map, "1")
        if cond.operator == "crosses_above":
            return f"(({left0} > {right0}) && ({left1} <= {right1}))"
        return f"(({left0} < {right0}) && ({left1} >= {right1}))"
    left = _mql5_render_scalar(cond.left, var_map, "0")
    right = _mql5_render_scalar(cond.right, var_map, "0")
    return f"({left} {cond.operator} {right})"


def _mql5_render_group(group: _ConditionGroup, var_map: dict[tuple, str]) -> str:
    if not group.conditions:
        return "false"
    parts = [_mql5_render_condition(c, var_map) for c in group.conditions]
    expr = parts[0]
    for i, connector in enumerate(group.connectors):
        if i + 1 < len(parts):
            op = "&&" if connector == "AND" else "||"
            expr = f"({expr} {op} {parts[i + 1]})"
    return expr


def to_mql5(config: dict) -> str:
    """Renders a Manual Strategy Builder config as a standalone MQL5
    Expert Advisor, ready to compile in MetaEditor and attach to a live
    or demo MT5 account. Uses CTrade + handle/CopyBuffer indicators (the
    modern MQL5 idiom), not the legacy OrderSend() calling style."""
    parsed = parse_manual_config(config)
    indicators = _collect_indicators(parsed)
    globals_, init_lines, tick_lines, var_map = _mql5_declare_indicators(indicators)

    # ATR-multiple stop/target need their own dedicated handle regardless of
    # whether the strategy's entry/exit conditions happen to reference an
    # ATR operand at the same period -- risk management is generated
    # independently of the condition expressions above.
    risk_atr_handles: dict[int, str] = {}
    for period in filter(None, [
        parsed.stop_atr_period if parsed.stop_type == "atr" else None,
        parsed.target_atr_period if parsed.target_type == "atr" else None,
    ]):
        if period in risk_atr_handles:
            continue
        handle = f"h_risk_atr_{period}"
        arr = f"{handle}_buf"
        globals_.append(f"int {handle};")
        globals_.append(f"double {arr}[];")
        init_lines.append(f"{handle} = iATR(_Symbol, PERIOD_CURRENT, {period});")
        tick_lines.append(f"ArraySetAsSeries({arr}, true);")
        tick_lines.append(f"CopyBuffer({handle}, 0, 0, 3, {arr});")
        risk_atr_handles[period] = arr

    allow_long = parsed.direction in ("long", "both")
    allow_short = parsed.direction in ("short", "both")

    lines: list[str] = []
    lines.append("//+------------------------------------------------------------------+")
    lines.append(f"//| {parsed.name[:64]:<64} |")
    lines.append("//| Generated by the T58 Universal Strategy Translator from a Manual  |")
    lines.append("//| Strategy Builder config. Review before trading a live account.    |")
    lines.append("//+------------------------------------------------------------------+")
    lines.append("#include <Trade\\Trade.mqh>")
    lines.append("CTrade trade;")
    lines.append("")
    lines.append('input double LotSize = 0.10;')
    lines.append("")
    lines.extend(globals_)
    if parsed.max_bars_in_trade:
        lines.append(f"// T58_MAX_BARS_IN_TRADE={parsed.max_bars_in_trade}")
        lines.append("int barsInTrade = 0;")
    lines.append("")

    lines.append("int OnInit()")
    lines.append("{")
    lines.extend(f"   {line}" for line in init_lines)
    lines.append("   return(INIT_SUCCEEDED);")
    lines.append("}")
    lines.append("")

    lines.append("void OnTick()")
    lines.append("{")
    lines.append("   if (Bars(_Symbol, PERIOD_CURRENT) < 50) return; // let indicators warm up")
    lines.extend(f"   {line}" for line in tick_lines)
    lines.append("")
    long_entry_expr = _mql5_render_group(parsed.long_entry if allow_long else _ConditionGroup((), ()), var_map)
    short_entry_expr = _mql5_render_group(parsed.short_entry if allow_short else _ConditionGroup((), ()), var_map)
    long_exit_expr = _mql5_render_group(parsed.long_exit, var_map)
    short_exit_expr = _mql5_render_group(parsed.short_exit, var_map)

    lines.append(f"   bool longEntryCond = {long_entry_expr};")
    lines.append(f"   bool shortEntryCond = {short_entry_expr};")
    lines.append(f"   bool longExitCond = {long_exit_expr};")
    lines.append(f"   bool shortExitCond = {short_exit_expr};")
    lines.append("")

    if parsed.max_bars_in_trade:
        lines.append("   if (PositionSelect(_Symbol)) { barsInTrade++; } else { barsInTrade = 0; }")
        lines.append(f"   bool maxBarsExit = barsInTrade >= {parsed.max_bars_in_trade};")
        lines.append("   longExitCond = longExitCond || maxBarsExit;")
        lines.append("   shortExitCond = shortExitCond || maxBarsExit;")
        lines.append("")

    if parsed.time_exit:
        try:
            hh, mm = (int(x) for x in parsed.time_exit.split(":")[:2])
        except ValueError:
            raise TranslationError(f"Time-based exit '{parsed.time_exit}' must be in HH:MM format.")
        lines.append(f"   // T58_TIME_EXIT={parsed.time_exit}")
        lines.append("   MqlDateTime tm; TimeToStruct(TimeCurrent(), tm);")
        lines.append(f"   bool timeExitCond = (tm.hour > {hh}) || (tm.hour == {hh} && tm.min >= {mm});")
        lines.append("   longExitCond = longExitCond || timeExitCond;")
        lines.append("   shortExitCond = shortExitCond || timeExitCond;")
        lines.append("")

    lines.append("   if (PositionSelect(_Symbol))")
    lines.append("   {")
    lines.append("      long posType = PositionGetInteger(POSITION_TYPE);")
    lines.append("      if (posType == POSITION_TYPE_BUY && longExitCond) trade.PositionClose(_Symbol);")
    lines.append("      if (posType == POSITION_TYPE_SELL && shortExitCond) trade.PositionClose(_Symbol);")
    lines.append("      return;")
    lines.append("   }")
    lines.append("")

    sl_tp_setup: list[str] = []
    if parsed.stop_type or parsed.target_type:
        sl_tp_setup.append('// T58_SL_PIPS / T58_SL_ATR_MULT below use the point size of THIS symbol.')
        if parsed.stop_type == "fixed":
            sl_tp_setup.append(f"   // T58_SL_PIPS={_fmt_num(parsed.stop_value)}")
            sl_tp_setup.append(f"   double slDist = {_fmt_num(parsed.stop_value)} * _Point;")
        elif parsed.stop_type == "atr":
            sl_tp_setup.append(f"   // T58_SL_ATR_MULT={_fmt_num(parsed.stop_value)}")
            sl_tp_setup.append(f"   // T58_ATR_PERIOD={parsed.stop_atr_period}")
            atr_expr = f"{risk_atr_handles[parsed.stop_atr_period]}[0]"
            sl_tp_setup.append(f"   double slDist = {atr_expr} * {_fmt_num(parsed.stop_value)};")
        if parsed.target_type == "fixed":
            sl_tp_setup.append(f"   // T58_TP_PIPS={_fmt_num(parsed.target_value)}")
            sl_tp_setup.append(f"   double tpDist = {_fmt_num(parsed.target_value)} * _Point;")
        elif parsed.target_type == "atr":
            sl_tp_setup.append(f"   // T58_TP_ATR_MULT={_fmt_num(parsed.target_value)}")
            sl_tp_setup.append(f"   // T58_ATR_PERIOD={parsed.target_atr_period}")
            atr_expr = f"{risk_atr_handles[parsed.target_atr_period]}[0]"
            sl_tp_setup.append(f"   double tpDist = {atr_expr} * {_fmt_num(parsed.target_value)};")

    lines.append("   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);")
    lines.append("   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);")
    lines.extend(sl_tp_setup)
    lines.append("")
    lines.append("   if (longEntryCond)")
    lines.append("   {")
    sl_long = "ask - slDist" if parsed.stop_type else "0"
    tp_long = "ask + tpDist" if parsed.target_type else "0"
    lines.append(f'      trade.Buy(LotSize, _Symbol, ask, {sl_long}, {tp_long});')
    lines.append("   }")
    lines.append("   else if (shortEntryCond)")
    lines.append("   {")
    sl_short = "bid + slDist" if parsed.stop_type else "0"
    tp_short = "bid - tpDist" if parsed.target_type else "0"
    lines.append(f'      trade.Sell(LotSize, _Symbol, bid, {sl_short}, {tp_short});')
    lines.append("   }")
    lines.append("}")
    lines.append("")
    if any(op.kind == "vwap" for op in indicators.values()):
        lines.append("// Session VWAP, matching app.strategy.indicators.vwap()'s own formula")
        lines.append("// exactly: cumulative (H+L+C)/3 * volume divided by cumulative volume,")
        lines.append("// reset at the start of each new day. Standard MQL5 has no built-in VWAP")
        lines.append("// indicator (unlike Pine's ta.vwap()), so this reproduces it directly from")
        lines.append("// historical rates rather than approximating with a moving average.")
        lines.append("double ComputeVWAP(int shift)")
        lines.append("{")
        lines.append("   MqlDateTime startDt;")
        lines.append("   TimeToStruct(iTime(_Symbol, PERIOD_CURRENT, shift), startDt);")
        lines.append("   double sumPV = 0.0, sumV = 0.0;")
        lines.append("   int total = Bars(_Symbol, PERIOD_CURRENT);")
        lines.append("   for (int i = shift; i < total; i++)")
        lines.append("   {")
        lines.append("      MqlDateTime dt;")
        lines.append("      TimeToStruct(iTime(_Symbol, PERIOD_CURRENT, i), dt);")
        lines.append("      if (dt.day != startDt.day || dt.mon != startDt.mon || dt.year != startDt.year) break;")
        lines.append("      double typical = (iHigh(_Symbol, PERIOD_CURRENT, i) + iLow(_Symbol, PERIOD_CURRENT, i) + iClose(_Symbol, PERIOD_CURRENT, i)) / 3.0;")
        lines.append("      double vol = (double)iVolume(_Symbol, PERIOD_CURRENT, i);")
        lines.append("      sumPV += typical * vol;")
        lines.append("      sumV += vol;")
        lines.append("   }")
        lines.append("   return sumV > 0.0 ? sumPV / sumV : 0.0;")
        lines.append("}")
        lines.append("")
    lines.extend(_risk_todo_lines(parsed, "//"))
    lines.extend(_config_directive_lines(config, "//"))
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Round-trip config directive (embedded in every generated file so it can be
# translated onward later without re-deriving a config from the code) --
# see the module docstring's "ROUND-TRIP FIDELITY" section.
# ---------------------------------------------------------------------------

_CONFIG_DIRECTIVE_RE = re.compile(r"T58_MANUAL_CONFIG_JSON=(\{.*\})\s*$")


def _config_directive_lines(config: dict, comment_prefix: str) -> list[str]:
    try:
        payload = json.dumps(config, separators=(",", ":"), default=str)
    except (TypeError, ValueError):
        return []
    return [
        "",
        f"{comment_prefix} Full round-trip config below -- lets the T58 Universal Strategy",
        f"{comment_prefix} Translator convert this file to another language later without",
        f"{comment_prefix} re-deriving one from the code above by hand. Do not remove.",
        f"{comment_prefix} T58_MANUAL_CONFIG_JSON={payload}",
    ]


def _extract_embedded_config(source_text: str) -> dict | None:
    for line in source_text.splitlines():
        m = _CONFIG_DIRECTIVE_RE.search(line)
        if m:
            try:
                return json.loads(m.group(1))
            except (json.JSONDecodeError, ValueError):
                continue
    return None


# ---------------------------------------------------------------------------
# Config <-> structured-condition dict rendering (shared by every reverse
# parser below to build a Manual Strategy Builder config dict from the
# _Operand/_Condition/_ConditionGroup objects a symbolic parse produces)
# ---------------------------------------------------------------------------

def _operand_to_dict(op: _Operand):
    if op.kind == "constant":
        return op.value
    if op.kind == "price":
        return {"type": "price", "field": op.field}
    return {"type": op.kind, "field": op.field, "period": op.period}


_OPERATOR_DISPLAY = {"crosses_above": "crosses above", "crosses_below": "crosses below"}


def _condition_to_dict(cond: _Condition) -> dict:
    return {
        "left": _operand_to_dict(cond.left),
        "operator": _OPERATOR_DISPLAY.get(cond.operator, cond.operator),
        "right": _operand_to_dict(cond.right),
    }


def _group_to_dict_pair(group: _ConditionGroup) -> tuple[list[dict], list[str]]:
    return [_condition_to_dict(c) for c in group.conditions], list(group.connectors)


def _merge_groups_or(groups: list[_ConditionGroup]) -> _ConditionGroup:
    """Combines several condition groups with OR between each -- mirrors
    app.strategy.pinescript.PineScriptStrategy._combine /
    app.strategy.mql5.MQL5Strategy._combine's own "multiple entry
    statements for the same side are OR'd together" behavior, just
    symbolically instead of over an evaluated boolean Series.

    SAFE ONLY when at most one group has more than one internal
    condition: _ConditionGroup has no nested sub-groups, only one flat
    left-to-right chain (see _pine_render_group/_mql5_render_group/
    _python_render_group, none of which apply real AND-before-OR
    precedence) -- so naively flattening two multi-condition groups with
    OR between them would silently change which conditions bind
    together (e.g. "(a and b) or (c and d)" flattened to the chain
    "a and b or c and d" renders as "((a and b) or c) and d", NOT the
    original grouping). Raises TranslationError in that case rather than
    emit code that looks right and isn't -- the same posture as every
    other unsupported construct in this module."""
    groups = [g for g in groups if g.conditions]
    if not groups:
        return _ConditionGroup((), ())
    if len(groups) == 1:
        return groups[0]
    if sum(1 for g in groups if len(g.conditions) > 1) > 0:
        raise TranslationError(
            "Multiple entry/exit guards, each combining more than one condition, can't be safely "
            "OR'd together in the manual config format -- it has no parenthesized sub-groups, so "
            "flattening them would silently change which conditions bind together. Rewrite this as "
            "a single guard, or translate each guard as its own strategy."
        )
    conditions = tuple(g.conditions[0] for g in groups)
    connectors = tuple("OR" for _ in range(len(groups) - 1))
    return _ConditionGroup(conditions, connectors)


# ---------------------------------------------------------------------------
# Shared symbolic boolean-expression resolver -- used by both the
# PineScript and MQL5 reverse parsers below. Pine's native `and`/`or`
# keywords and MQL5's `&&`/`||` (converted to `and`/`or` by the MQL5
# parser before reaching here) feed the exact same resolver, since once
# normalized to "and"/"or" the two languages' boolean-condition subsets
# this module supports are identical: named-variable/price/constant
# operands compared with > >= < <= == !=, joined left-to-right by and/or.
# ---------------------------------------------------------------------------

_AND_OR_RE = re.compile(r"\s+(and|or)\s+", re.IGNORECASE)
_COMPARISON_OPS = (">=", "<=", "==", "!=", ">", "<")
_AVERAGED_PRICE_ALIASES = {"hl2", "hlc3", "ohlc4"}


def _fully_wrapped(expr: str) -> bool:
    """True if expr starts and ends with a SINGLE matching pair of
    parens wrapping the whole expression (not e.g. "(a) and (b)", which
    merely starts with '(' and ends with ')')."""
    if not (expr.startswith("(") and expr.endswith(")")):
        return False
    depth = 0
    for i, ch in enumerate(expr):
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0 and i != len(expr) - 1:
                return False
    return depth == 0


def _split_top_level_bool(expr: str) -> tuple[list[str], list[str]]:
    """Splits `expr` into atomic terms and AND/OR connectors, only at
    paren-depth 0 -- exactly mirroring how left-to-right connectors chain
    in this module's own _ConditionGroup (see _pine_render_group /
    _mql5_render_group), which is why a plain left-to-right split (no
    real AND-before-OR precedence) round-trips correctly against this
    module's own renderers."""
    terms: list[str] = []
    connectors: list[str] = []
    depth = 0
    last = 0
    i = 0
    n = len(expr)
    while i < n:
        ch = expr[i]
        if ch == "(":
            depth += 1
            i += 1
            continue
        if ch == ")":
            depth -= 1
            i += 1
            continue
        if depth == 0:
            m = _AND_OR_RE.match(expr, i)
            if m:
                terms.append(expr[last:i].strip())
                connectors.append(m.group(1).upper())
                i = m.end()
                last = i
                continue
        i += 1
    terms.append(expr[last:].strip())
    return terms, connectors


def _split_comparison(expr: str) -> tuple[str, str, str] | None:
    for op in _COMPARISON_OPS:
        idx = expr.find(op)
        if idx > 0:
            return expr[:idx].strip(), op, expr[idx + len(op):].strip()
    return None


def _resolve_operand_token(token: str, var_defs: dict[str, _Operand]) -> _Operand:
    token = token.strip()
    try:
        return _Operand(kind="constant", value=float(token))
    except ValueError:
        pass
    if token in _PRICE_FIELDS:
        return _Operand(kind="price", field=token)
    if token in _AVERAGED_PRICE_ALIASES:
        raise TranslationError(
            f"'{token}' is an averaged price source (no single OHLC field backs it) with no "
            "equivalent operand in the manual config format -- rewrite the source using "
            "open/high/low/close directly, or translate a version of this strategy that already "
            "does."
        )
    if token in var_defs:
        return var_defs[token]
    raise TranslationError(f"Unsupported/unknown operand '{token}' for reverse translation.")


def _resolve_group(
    expr: str,
    var_defs: dict[str, _Operand],
    group_defs: dict[str, _ConditionGroup],
    cross_resolver=None,
) -> _ConditionGroup:
    expr = expr.strip()
    while _fully_wrapped(expr):
        expr = expr[1:-1].strip()
    if expr in group_defs:
        return group_defs[expr]
    if cross_resolver is not None:
        cross_group = cross_resolver(expr, var_defs)
        if cross_group is not None:
            return cross_group

    terms, connectors = _split_top_level_bool(expr)
    if len(terms) == 1:
        comp = _split_comparison(terms[0])
        if comp is None:
            raise TranslationError(f"Unsupported condition expression '{expr}' for reverse translation.")
        left_tok, op, right_tok = comp
        left = _resolve_operand_token(left_tok, var_defs)
        right = _resolve_operand_token(right_tok, var_defs)
        return _ConditionGroup((_Condition(left, _normalize_operator(op), right),), ())

    all_conditions: list = []
    all_connectors: list = []
    for idx, term in enumerate(terms):
        sub = _resolve_group(term, var_defs, group_defs, cross_resolver)
        if not sub.conditions:
            raise TranslationError(f"Empty condition term '{term}' for reverse translation.")
        if idx > 0:
            all_connectors.append(connectors[idx - 1])
        all_conditions.extend(sub.conditions)
        all_connectors.extend(sub.connectors)
    return _ConditionGroup(tuple(all_conditions), tuple(all_connectors))


def _config_from_groups(
    name: str,
    long_entry: _ConditionGroup, short_entry: _ConditionGroup,
    long_exit: _ConditionGroup, short_exit: _ConditionGroup,
    stop_loss_pips, take_profit_pips, sl_atr_mult, tp_atr_mult, atr_period,
) -> dict:
    if long_entry.conditions and short_entry.conditions:
        direction = "both"
    elif long_entry.conditions:
        direction = "long"
    else:
        direction = "short"

    long_conds, long_conns = _group_to_dict_pair(long_entry)
    short_conds, short_conns = _group_to_dict_pair(short_entry)
    lx_conds, lx_conns = _group_to_dict_pair(long_exit)
    sx_conds, sx_conns = _group_to_dict_pair(short_exit)

    config: dict = {
        "name": name,
        "market": {"direction": direction},
        "entry_conditions": {
            "long": long_conds, "long_connectors": long_conns,
            "short": short_conds, "short_connectors": short_conns,
        },
        "exit_conditions": {
            "long": lx_conds, "long_connectors": lx_conns,
            "short": sx_conds, "short_connectors": sx_conns,
        },
        "risk_management": {},
    }
    rm = config["risk_management"]
    if sl_atr_mult is not None:
        rm["stop_type"], rm["stop_value"], rm["stop_atr_period"] = "atr", sl_atr_mult, atr_period
    elif stop_loss_pips is not None:
        rm["stop_type"], rm["stop_value"] = "fixed", stop_loss_pips
    if tp_atr_mult is not None:
        rm["target_type"], rm["target_value"], rm["target_atr_period"] = "atr", tp_atr_mult, atr_period
    elif take_profit_pips is not None:
        rm["target_type"], rm["target_value"] = "fixed", take_profit_pips
    return config


# ---------------------------------------------------------------------------
# PineScript reverse parsing (PineScript -> Manual Strategy Builder config)
# ---------------------------------------------------------------------------

_PINE_ASSIGN_RE = re.compile(r"^\s*(?:var\s+)?([A-Za-z_]\w*)\s*=\s*(.+?)\s*$")
_PINE_TA_CALL_RE = re.compile(r"ta\.(sma|ema|wma|rsi)\s*\(\s*([^,()]+)\s*,\s*([^()]+)\s*\)")
_PINE_VWAP_CALL_RE = re.compile(r"ta\.vwap\s*\(\s*[^()]*\s*\)")
_PINE_CROSS_CALL_RE = re.compile(r"ta\.(crossover|crossunder)\s*\(\s*([^,()]+)\s*,\s*([^()]+)\s*\)")
_PINE_INPUT_RE = re.compile(r"input\.(?:int|float)\s*\(\s*([-\d.]+)")
_PINE_IF_RE = re.compile(r"^(\s*)if\s+(.+?)\s*$")
_PINE_ENTRY_RE = re.compile(
    r'strategy\.entry\s*\(\s*"([^"]*)"\s*,\s*strategy\.(long|short)\s*(?:,.*?when\s*=\s*(.+?))?\s*\)'
)
_PINE_CLOSE_RE = re.compile(r'strategy\.close\s*\(\s*"([^"]*)"\s*(?:,.*?when\s*=\s*(.+?))?\s*\)')
_PINE_SL_RE = re.compile(r"T58_SL_PIPS\s*=\s*([\d.]+)")
_PINE_TP_RE = re.compile(r"T58_TP_PIPS\s*=\s*([\d.]+)")
_PINE_SL_ATR_RE = re.compile(r"T58_SL_ATR_MULT\s*=\s*([\d.]+)")
_PINE_TP_ATR_RE = re.compile(r"T58_TP_ATR_MULT\s*=\s*([\d.]+)")
_PINE_ATR_PERIOD_RE = re.compile(r"T58_ATR_PERIOD\s*=\s*(\d+)")


def _pine_strip_comment(line: str) -> tuple[str, str]:
    in_str = False
    for i, ch in enumerate(line):
        if ch == '"':
            in_str = not in_str
        elif ch == "/" and not in_str and i + 1 < len(line) and line[i + 1] == "/":
            return line[:i], line[i:]
    return line, ""


def _pine_join_continuation_lines(raw_lines: list[str]) -> list[str]:
    joined: list[str] = []
    buffer: list[str] = []
    depth = 0
    for raw_line in raw_lines:
        code, _ = _pine_strip_comment(raw_line)
        buffer.append(raw_line)
        depth += code.count("(") - code.count(")")
        if depth <= 0 or len(buffer) >= 20:
            joined.append(" ".join(buffer) if len(buffer) > 1 else buffer[0])
            buffer = []
            depth = 0
    if buffer:
        joined.append(" ".join(buffer) if len(buffer) > 1 else buffer[0])
    return joined


def _pine_cross_resolver(expr: str, var_defs: dict[str, _Operand]):
    m = _PINE_CROSS_CALL_RE.match(expr)
    if not m or m.group(0) != expr:
        return None
    func, a_tok, b_tok = m.groups()
    left = _resolve_operand_token(a_tok, var_defs)
    right = _resolve_operand_token(b_tok, var_defs)
    op = "crosses_above" if func == "crossover" else "crosses_below"
    return _ConditionGroup((_Condition(left, op, right),), ())


def _pine_resolve_length(token: str, var_defs: dict[str, _Operand]) -> int:
    token = token.strip()
    try:
        return int(float(token))
    except ValueError:
        pass
    op = var_defs.get(token)
    if op is not None and op.kind == "constant":
        return int(op.value)
    raise TranslationError(f"PineScript: could not resolve length argument '{token}' to a number.")


def _parse_pinescript_from_code(source: str) -> dict:
    var_defs: dict[str, _Operand] = {}
    group_defs: dict[str, _ConditionGroup] = {}

    stop_loss_pips = take_profit_pips = None
    sl_atr_mult = tp_atr_mult = None
    atr_period = 14

    long_entry_groups: list[_ConditionGroup] = []
    short_entry_groups: list[_ConditionGroup] = []
    long_exit_groups: list[_ConditionGroup] = []
    short_exit_groups: list[_ConditionGroup] = []

    if_stack: list[tuple[int, _ConditionGroup]] = []

    for raw_line in _pine_join_continuation_lines(source.splitlines()):
        code, comment = _pine_strip_comment(raw_line)

        m = _PINE_SL_RE.search(comment)
        if m:
            stop_loss_pips = float(m.group(1))
        m = _PINE_TP_RE.search(comment)
        if m:
            take_profit_pips = float(m.group(1))
        m = _PINE_SL_ATR_RE.search(comment)
        if m:
            sl_atr_mult = float(m.group(1))
        m = _PINE_TP_ATR_RE.search(comment)
        if m:
            tp_atr_mult = float(m.group(1))
        m = _PINE_ATR_PERIOD_RE.search(comment)
        if m:
            atr_period = int(m.group(1))

        if not code.strip():
            continue

        indent = len(code) - len(code.lstrip(" "))
        while if_stack and indent <= if_stack[-1][0]:
            if_stack.pop()

        if_match = _PINE_IF_RE.match(code)
        if if_match:
            cond_indent = len(if_match.group(1))
            group = _resolve_group(if_match.group(2).strip(), var_defs, group_defs, _pine_cross_resolver)
            if_stack.append((cond_indent, group))
            continue

        assign_match = _PINE_ASSIGN_RE.match(code)
        if assign_match:
            var_name, rhs = assign_match.groups()

            input_match = _PINE_INPUT_RE.search(rhs)
            if input_match and rhs.strip().startswith("input."):
                var_defs[var_name] = _Operand(kind="constant", value=float(input_match.group(1)))
                continue

            cross_match = _PINE_CROSS_CALL_RE.search(rhs)
            if cross_match:
                func, a_tok, b_tok = cross_match.groups()
                left = _resolve_operand_token(a_tok, var_defs)
                right = _resolve_operand_token(b_tok, var_defs)
                op = "crosses_above" if func == "crossover" else "crosses_below"
                group_defs[var_name] = _ConditionGroup((_Condition(left, op, right),), ())
                continue

            vwap_match = _PINE_VWAP_CALL_RE.search(rhs)
            if vwap_match:
                # ta.vwap()'s argument is always an averaged/typical price
                # source (hlc3 in this tool's own output, sometimes close
                # in hand-written scripts) -- that's normal for VWAP
                # specifically and doesn't hit the "averaged price source"
                # rejection below, since VWAP's own manual-config operand
                # (see app.strategy.indicators.vwap) always uses (H+L+C)/3
                # regardless of what's written here.
                var_defs[var_name] = _Operand(kind="vwap", field="close", period=14)
                continue

            ta_match = _PINE_TA_CALL_RE.search(rhs)
            if ta_match:
                func, src_tok, len_tok = ta_match.groups()
                src_tok = src_tok.strip()
                if src_tok in _AVERAGED_PRICE_ALIASES:
                    raise TranslationError(
                        f"PineScript: '{func}' is computed from '{src_tok}', an averaged price source "
                        "with no equivalent single price field in the manual config format."
                    )
                if src_tok not in _PRICE_FIELDS:
                    raise TranslationError(
                        f"PineScript: '{func}({src_tok}, ...)' -- indicators computed from another "
                        "indicator's output (rather than a plain price field) aren't representable "
                        "in the manual config format."
                    )
                period = _pine_resolve_length(len_tok, var_defs)
                var_defs[var_name] = _Operand(kind=func, field=src_tok, period=period)
                continue

            if any(op in rhs for op in ("<", ">", "==", "!=", " and ", " or ")):
                group_defs[var_name] = _resolve_group(rhs.strip(), var_defs, group_defs, _pine_cross_resolver)
                continue

            if rhs.strip() in _PRICE_FIELDS:
                var_defs[var_name] = _Operand(kind="price", field=rhs.strip())
                continue
            if rhs.strip() in _AVERAGED_PRICE_ALIASES:
                raise TranslationError(
                    f"PineScript: '{var_name} = {rhs.strip()}' -- averaged price sources have no "
                    "equivalent single price field in the manual config format."
                )

            raise TranslationError(
                f"PineScript: unsupported expression '{var_name} = {rhs}' for reverse translation."
            )

        entry_match = _PINE_ENTRY_RE.search(code)
        if entry_match:
            _, direction, when_expr = entry_match.groups()
            group = _pine_condition_for_statement(when_expr, if_stack, var_defs, group_defs)
            (long_entry_groups if direction == "long" else short_entry_groups).append(group)
            continue

        close_match = _PINE_CLOSE_RE.search(code)
        if close_match:
            trade_id, when_expr = close_match.groups()
            group = _pine_condition_for_statement(when_expr, if_stack, var_defs, group_defs)
            tid = (trade_id or "").lower()
            if "short" in tid:
                short_exit_groups.append(group)
            elif "long" in tid:
                long_exit_groups.append(group)
            else:
                long_exit_groups.append(group)
                short_exit_groups.append(group)
            continue

        # anything else (plotting, alerts, the strategy() declaration header,
        # etc.) is silently ignored, same as the forward parser

    if not long_entry_groups and not short_entry_groups:
        raise TranslationError(
            "PineScript: no strategy.entry(...) call was found -- nothing to translate. This "
            "parser supports the same subset app/strategy/pinescript.py's backtest importer does."
        )

    config = _config_from_groups(
        "Translated PineScript Strategy",
        _merge_groups_or(long_entry_groups), _merge_groups_or(short_entry_groups),
        _merge_groups_or(long_exit_groups), _merge_groups_or(short_exit_groups),
        stop_loss_pips, take_profit_pips, sl_atr_mult, tp_atr_mult, atr_period,
    )
    return config


def _pine_condition_for_statement(when_expr, if_stack, var_defs, group_defs) -> _ConditionGroup:
    if when_expr:
        return _resolve_group(when_expr.strip(), var_defs, group_defs, _pine_cross_resolver)
    if if_stack:
        return if_stack[-1][1]
    raise TranslationError(
        "PineScript: a strategy.entry()/strategy.close() call has no when= condition and is not "
        "inside an `if` block -- cannot determine when it should trigger."
    )


def parse_pinescript(source: str) -> dict:
    """Reverse-parses PineScript v5 source (the same subset
    app.strategy.pinescript.PineScriptStrategy already backtests) back
    into a Manual Strategy Builder config dict, so it can be translated
    onward into Python or MQL5. Prefers this module's own embedded
    T58_MANUAL_CONFIG_JSON round-trip directive when present (see module
    docstring) for perfect fidelity; otherwise derives a config from the
    code itself, raising TranslationError on anything outside the
    supported subset rather than guessing."""
    embedded = _extract_embedded_config(source)
    if embedded is not None:
        return embedded
    return _parse_pinescript_from_code(source)


# ---------------------------------------------------------------------------
# MQL5 reverse parsing (MQL5 -> Manual Strategy Builder config)
# ---------------------------------------------------------------------------

_MQL5_ASSIGN_RE = re.compile(r"^\s*(?:double|int|bool)?\s*([A-Za-z_]\w*)\s*=\s*(.+?);\s*$")
_MQL5_IMA_RE = re.compile(r"iMA\s*\([^,]+,[^,]+,\s*([^,]+),[^,]+,\s*(MODE_\w+)\s*,[^)]*\)")
_MQL5_IRSI_RE = re.compile(r"iRSI\s*\([^,]+,[^,]+,\s*([^,]+),[^)]*\)")
_MQL5_IF_BLOCK_RE = re.compile(r"^(\s*)if\s*\((.+)\)\s*\{\s*$")
_MQL5_IF_INLINE_RE = re.compile(r"^(\s*)if\s*\((.+?)\)\s*([^\{].*);\s*$")
_MQL5_BARE_IF_RE = re.compile(r"^\s*if\s*\((.+)\)\s*$")
_MQL5_BUY_RE = re.compile(r"trade\.Buy\s*\(|OrderSend\s*\([^)]*(?:ORDER_TYPE_BUY|OP_BUY)")
_MQL5_SELL_RE = re.compile(r"trade\.Sell\s*\(|OrderSend\s*\([^)]*(?:ORDER_TYPE_SELL|OP_SELL)")
_MQL5_CLOSE_RE = re.compile(r"trade\.PositionClose\s*\(|OrderClose\s*\(")
_MQL5_LINE_COMMENT_RE = re.compile(r"//.*$")
_MQL5_BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
_MQL5_MODE_TO_KIND = {"MODE_SMA": "sma", "MODE_EMA": "ema", "MODE_LWMA": "wma"}


def _mql5_bool_to_generic(expr: str) -> str:
    expr = re.sub(r"&&", " and ", expr)
    expr = re.sub(r"\|\|", " or ", expr)
    return expr.strip()


def _parse_mql5_from_code(source: str) -> dict:
    code = _MQL5_BLOCK_COMMENT_RE.sub("", source)

    var_defs: dict[str, _Operand] = {}
    group_defs: dict[str, _ConditionGroup] = {}

    stop_loss_pips = take_profit_pips = None
    sl_atr_mult = tp_atr_mult = None
    atr_period = 14

    long_entry_groups: list[_ConditionGroup] = []
    short_entry_groups: list[_ConditionGroup] = []
    exit_groups: list[_ConditionGroup] = []

    if_stack: list[tuple[int, _ConditionGroup]] = []
    brace_depth = 0
    pending_cond: _ConditionGroup | None = None

    def materialize(cond_raw: str) -> _ConditionGroup:
        return _resolve_group(_mql5_bool_to_generic(cond_raw), var_defs, group_defs)

    def active_guard():
        return if_stack[-1][1] if if_stack else None

    for raw_line in code.splitlines():
        no_comment = _MQL5_LINE_COMMENT_RE.sub("", raw_line)

        m = _PINE_SL_RE.search(raw_line)
        if m:
            stop_loss_pips = float(m.group(1))
        m = _PINE_TP_RE.search(raw_line)
        if m:
            take_profit_pips = float(m.group(1))
        m = _PINE_SL_ATR_RE.search(raw_line)
        if m:
            sl_atr_mult = float(m.group(1))
        m = _PINE_TP_ATR_RE.search(raw_line)
        if m:
            tp_atr_mult = float(m.group(1))
        m = _PINE_ATR_PERIOD_RE.search(raw_line)
        if m:
            atr_period = int(m.group(1))

        line = no_comment.strip()
        if not line:
            continue

        if pending_cond is not None:
            if line == "{":
                if_stack.append((brace_depth, pending_cond))
                brace_depth += 1
                pending_cond = None
                continue
            guard = pending_cond
            pending_cond = None
            if _MQL5_BUY_RE.search(line):
                long_entry_groups.append(guard)
            elif _MQL5_SELL_RE.search(line):
                short_entry_groups.append(guard)
            elif _MQL5_CLOSE_RE.search(line):
                exit_groups.append(guard)
            continue

        if "}" in line:
            for _ in range(line.count("}")):
                brace_depth = max(0, brace_depth - 1)
                if if_stack and brace_depth == if_stack[-1][0]:
                    if_stack.pop()
            remainder = line.replace("}", "").strip()
            if not remainder:
                continue
            line = remainder

        assign_match = _MQL5_ASSIGN_RE.match(line)
        if assign_match:
            var_name, rhs = assign_match.groups()

            ima_match = _MQL5_IMA_RE.search(rhs)
            if ima_match:
                period_tok, mode = ima_match.groups()
                try:
                    period = int(float(period_tok.strip()))
                except ValueError:
                    raise TranslationError(f"MQL5: could not resolve iMA period '{period_tok}'.")
                kind = _MQL5_MODE_TO_KIND.get(mode, "sma")
                var_defs[var_name] = _Operand(kind=kind, field="close", period=period)
                continue

            irsi_match = _MQL5_IRSI_RE.search(rhs)
            if irsi_match:
                period_tok = irsi_match.group(1)
                try:
                    period = int(float(period_tok.strip()))
                except ValueError:
                    raise TranslationError(f"MQL5: could not resolve iRSI period '{period_tok}'.")
                var_defs[var_name] = _Operand(kind="rsi", field="close", period=period)
                continue

            if any(op in rhs for op in ("<", ">", "==", "!=", "&&", "||")):
                group_defs[var_name] = _resolve_group(_mql5_bool_to_generic(rhs), var_defs, group_defs)
                continue

            try:
                var_defs[var_name] = _Operand(kind="constant", value=float(rhs.strip()))
                continue
            except ValueError:
                pass

            raise TranslationError(
                f"MQL5: unsupported expression assigned to '{var_name}': '{rhs}' for reverse translation. "
                "Supported: iMA(...) with MODE_SMA/MODE_EMA/MODE_LWMA, iRSI(...), boolean comparisons, "
                "and numeric literals."
            )

        block_match = _MQL5_IF_BLOCK_RE.match(line)
        if block_match:
            group = materialize(block_match.group(2))
            if_stack.append((brace_depth, group))
            brace_depth += 1
            continue

        inline_match = _MQL5_IF_INLINE_RE.match(line)
        if inline_match:
            group = materialize(inline_match.group(2))
            stmt = inline_match.group(3)
            if _MQL5_BUY_RE.search(stmt):
                long_entry_groups.append(group)
            elif _MQL5_SELL_RE.search(stmt):
                short_entry_groups.append(group)
            elif _MQL5_CLOSE_RE.search(stmt):
                exit_groups.append(group)
            continue

        bare_if_match = _MQL5_BARE_IF_RE.match(line)
        if bare_if_match:
            pending_cond = materialize(bare_if_match.group(1))
            continue

        if line == "{" or line.endswith("{"):
            brace_depth += 1
            continue

        guard = active_guard()
        if _MQL5_BUY_RE.search(line):
            if guard is None:
                raise TranslationError("MQL5: found a Buy/OrderSend(BUY) call not guarded by an `if` condition.")
            long_entry_groups.append(guard)
            continue
        if _MQL5_SELL_RE.search(line):
            if guard is None:
                raise TranslationError("MQL5: found a Sell/OrderSend(SELL) call not guarded by an `if` condition.")
            short_entry_groups.append(guard)
            continue
        if _MQL5_CLOSE_RE.search(line):
            if guard is not None:
                exit_groups.append(guard)
            continue

        # anything else (OnInit/OnTick declarations, bookkeeping, etc.) is
        # silently ignored, same as the forward parser

    if not long_entry_groups and not short_entry_groups:
        raise TranslationError(
            "MQL5: no Buy/Sell (trade.Buy/trade.Sell/OrderSend) call was found inside a recognizable "
            "`if` condition -- nothing to translate. This parser supports the same subset "
            "app/strategy/mql5.py's backtest importer does."
        )

    # This parser's MQL5 subset has no per-side (long vs short) exit
    # distinction -- every trade.PositionClose(...) guard applies to
    # whichever side is open, matching app.strategy.mql5.MQL5Strategy's
    # own "EXIT SCOPE LIMIT" (see that module's forward parser docstring).
    exit_group = _merge_groups_or(exit_groups)
    config = _config_from_groups(
        "Translated MQL5 Strategy",
        _merge_groups_or(long_entry_groups), _merge_groups_or(short_entry_groups),
        exit_group, exit_group,
        stop_loss_pips, take_profit_pips, sl_atr_mult, tp_atr_mult, atr_period,
    )
    return config


def parse_mql5(source: str) -> dict:
    """Reverse-parses MQL5 source (the same subset
    app.strategy.mql5.MQL5Strategy already backtests) back into a Manual
    Strategy Builder config dict. Prefers this module's own embedded
    T58_MANUAL_CONFIG_JSON round-trip directive when present (see module
    docstring); otherwise derives a config from the code, raising
    TranslationError on anything outside the supported subset."""
    embedded = _extract_embedded_config(source)
    if embedded is not None:
        return embedded
    return _parse_mql5_from_code(source)


# ---------------------------------------------------------------------------
# Python generation (Manual Strategy Builder config -> Python)
# ---------------------------------------------------------------------------

_PYTHON_IMPORTS = (
    "from app.strategy.indicators import (\n"
    "    atr, bollinger, crossover, crossunder, ema, highest_high, lowest_low, macd, rsi, sma, vwap, wma,\n"
    ")"
)


def _python_declare_indicators(indicators: dict[tuple, _Operand]) -> tuple[list[str], dict[tuple, str]]:
    lines: list[str] = []
    var_map: dict[tuple, str] = {}

    def src(field_name: str) -> str:
        return f"work['{field_name}']" if field_name in _PRICE_FIELDS else "work['close']"

    macd_fields = sorted({op.field for op in indicators.values() if op.kind in ("macd", "macd_signal", "macd_histogram")})
    for fld in macd_fields:
        base = f"macd_{fld}"
        lines.append(f"{base}_line, {base}_signal, {base}_hist = macd({src(fld)}, 12, 26, 9)")
        var_map[("macd", fld, 0)] = f"{base}_line"
        var_map[("macd_signal", fld, 0)] = f"{base}_signal"
        var_map[("macd_histogram", fld, 0)] = f"{base}_hist"

    bb_groups = sorted({(op.field, op.period) for op in indicators.values()
                         if op.kind in ("bollinger_mid", "bollinger_upper", "bollinger_lower")})
    for fld, period in bb_groups:
        base = f"bb_{fld}_{period}"
        lines.append(f"{base}_mid, {base}_upper, {base}_lower = bollinger({src(fld)}, {period}, 2.0)")
        var_map[("bollinger_mid", fld, period)] = f"{base}_mid"
        var_map[("bollinger_upper", fld, period)] = f"{base}_upper"
        var_map[("bollinger_lower", fld, period)] = f"{base}_lower"

    for key, op in indicators.items():
        if op.kind in ("macd", "macd_signal", "macd_histogram", "bollinger_mid", "bollinger_upper", "bollinger_lower"):
            continue
        name = f"vwap_{op.field}" if op.kind == "vwap" else f"{op.kind}_{op.period}_{op.field}"
        if op.kind == "sma":
            lines.append(f"{name} = sma({src(op.field)}, {op.period})")
        elif op.kind == "ema":
            lines.append(f"{name} = ema({src(op.field)}, {op.period})")
        elif op.kind == "wma":
            lines.append(f"{name} = wma({src(op.field)}, {op.period})")
        elif op.kind == "rsi":
            lines.append(f"{name} = rsi({src(op.field)}, {op.period})")
        elif op.kind == "atr":
            lines.append(f"{name} = atr(work, {op.period})")
        elif op.kind == "highest_high":
            lines.append(f"{name} = highest_high(work['high'], {op.period})")
        elif op.kind == "lowest_low":
            lines.append(f"{name} = lowest_low(work['low'], {op.period})")
        elif op.kind == "vwap":
            # Ignores op.field -- app.strategy.indicators.vwap() always
            # derives typical price from H/L/C and needs the whole frame
            # (for its timestamp-based daily reset), not a single column.
            lines.append(f"{name} = vwap(work)")
        elif op.kind == "candle_direction":
            lines.append(f"{name} = (work['close'] - work['open']).apply(lambda d: 1 if d > 0 else (-1 if d < 0 else 0))")
        else:  # pragma: no cover -- guarded by _SUPPORTED_INDICATOR_KINDS
            raise TranslationError(f"Unhandled indicator kind '{op.kind}' during Python generation.")
        var_map[key] = name

    return lines, var_map


def _python_render_operand(op: _Operand, var_map: dict[tuple, str]) -> str:
    if op.kind == "constant":
        return _fmt_num(op.value)
    if op.kind == "price":
        return f"work['{op.field}']"
    return var_map[op.key()]


def _python_render_condition(cond: _Condition, var_map: dict[tuple, str]) -> str:
    left = _python_render_operand(cond.left, var_map)
    right = _python_render_operand(cond.right, var_map)
    if cond.operator == "crosses_above":
        return f"crossover({left}, {right})"
    if cond.operator == "crosses_below":
        return f"crossunder({left}, {right})"
    return f"({left} {cond.operator} {right})"


def _python_render_group(group: _ConditionGroup, var_map: dict[tuple, str]) -> str:
    if not group.conditions:
        return "pd.Series(False, index=work.index)"
    parts = [_python_render_condition(c, var_map) for c in group.conditions]
    expr = parts[0]
    for i, connector in enumerate(group.connectors):
        if i + 1 < len(parts):
            op = "&" if connector == "AND" else "|"
            expr = f"({expr}) {op} ({parts[i + 1]})"
    return expr


def to_python(config: dict) -> str:
    """Renders a Manual Strategy Builder config as a standalone
    `generate_signals(df)` Python module, ready to save into the Strategy
    Library's python/ folder and run through this app's own PythonStrategy
    adapter (see app/strategy/python.py) -- no separate platform needed,
    unlike the PineScript/MQL5 targets. ATR-based stop/target and the
    trailing-stop/break-even risk settings this module's Pine/MQL5
    renderers can only TODO-comment (see _risk_todo_lines) are genuinely
    implemented here instead, since PythonStrategy's signals.attrs
    contract (see that module's docstring) supports all of them natively.
    """
    parsed = parse_manual_config(config)
    indicators = _collect_indicators(parsed)
    indicator_lines, var_map = _python_declare_indicators(indicators)

    allow_long = parsed.direction in ("long", "both")
    allow_short = parsed.direction in ("short", "both")
    needs_loop_exit = bool(parsed.max_bars_in_trade or parsed.time_exit)

    lines: list[str] = []
    lines.append('"""')
    lines.append(parsed.name)
    lines.append("")
    lines.append("Generated by the T58 Universal Strategy Translator from a Manual Strategy")
    lines.append("Builder config. Review before running against real or paper capital.")
    lines.append('"""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import pandas as pd")
    lines.append("")
    lines.append(_PYTHON_IMPORTS)
    lines.append("")
    lines.append(f'STRATEGY_NAME = "{parsed.name}"')
    if parsed.stop_type == "fixed":
        lines.append(f"STOP_LOSS_PIPS = {_fmt_num(parsed.stop_value)}")
    if parsed.target_type == "fixed":
        lines.append(f"TAKE_PROFIT_PIPS = {_fmt_num(parsed.target_value)}")
    lines.append("")
    lines.append("")
    lines.append("def generate_signals(df: pd.DataFrame) -> pd.Series:")
    lines.append("    work = df.copy()")
    for l in indicator_lines:
        lines.append(f"    {l}")
    lines.append("")
    lines.append(f"    long_entry = {_python_render_group(parsed.long_entry if allow_long else _ConditionGroup((), ()), var_map)}")
    lines.append(f"    short_entry = {_python_render_group(parsed.short_entry if allow_short else _ConditionGroup((), ()), var_map)}")
    lines.append(f"    long_exit = {_python_render_group(parsed.long_exit, var_map)}")
    lines.append(f"    short_exit = {_python_render_group(parsed.short_exit, var_map)}")
    lines.append("")

    if not needs_loop_exit:
        lines.append("    from app.strategy.base import signals_from_conditions")
        lines.append("    signals = signals_from_conditions(work.index, long_entry, long_exit, short_entry, short_exit)")
    else:
        lines.append("    le = long_entry.to_numpy(); lx = long_exit.to_numpy()")
        lines.append("    se = short_entry.to_numpy(); sx = short_exit.to_numpy()")
        if parsed.time_exit:
            try:
                hh, mm = (int(x) for x in parsed.time_exit.split(":")[:2])
            except ValueError:
                raise TranslationError(f"Time-based exit '{parsed.time_exit}' must be in HH:MM format.")
            lines.append("    ts = pd.to_datetime(work['timestamp'])")
        lines.append("    position = 0")
        lines.append("    bars_in_trade = 0")
        lines.append("    out = [0] * len(work)")
        lines.append("    for i in range(len(work)):")
        lines.append("        forced_exit = False")
        lines.append("        if position != 0:")
        lines.append("            bars_in_trade += 1")
        if parsed.max_bars_in_trade:
            lines.append(f"            if bars_in_trade >= {parsed.max_bars_in_trade}:")
            lines.append("                forced_exit = True")
        if parsed.time_exit:
            lines.append(f"            if (ts.iloc[i].hour, ts.iloc[i].minute) >= ({hh}, {mm}):")
            lines.append("                forced_exit = True")
        lines.append("        if position == 0:")
        lines.append("            if le[i]:")
        lines.append("                position = 1; bars_in_trade = 0")
        lines.append("            elif se[i]:")
        lines.append("                position = -1; bars_in_trade = 0")
        lines.append("        elif position == 1:")
        lines.append("            if lx[i] or forced_exit:")
        lines.append("                position = 0")
        lines.append("            elif se[i]:")
        lines.append("                position = -1; bars_in_trade = 0")
        lines.append("        else:")
        lines.append("            if sx[i] or forced_exit:")
        lines.append("                position = 0")
        lines.append("            elif le[i]:")
        lines.append("                position = 1; bars_in_trade = 0")
        lines.append("        out[i] = position")
        lines.append("    signals = pd.Series(out, index=work.index)")

    lines.append("")
    if parsed.stop_type == "atr":
        lines.append(f"    signals.attrs['stop_loss_distance'] = atr(work, {parsed.stop_atr_period}) * {_fmt_num(parsed.stop_value)}")
    if parsed.target_type == "atr":
        lines.append(f"    signals.attrs['take_profit_distance'] = atr(work, {parsed.target_atr_period}) * {_fmt_num(parsed.target_value)}")
    if parsed.trailing_enabled:
        lines.append(f"    signals.attrs['trailing_stop_distance'] = atr(work, {parsed.trailing_atr_period}) * {_fmt_num(parsed.trailing_value)}")
    if parsed.breakeven_enabled:
        lines.append(f"    signals.attrs['breakeven_trigger_r'] = {_fmt_num(parsed.breakeven_trigger_r)}")
    lines.append("    return signals")
    lines.extend(_config_directive_lines(config, "#"))
    return "\n".join(lines).rstrip() + "\n"


def parse_python(source: str) -> dict:
    """Python strategies are arbitrary `generate_signals(df)` code (loops,
    custom indicators, arbitrary pandas expressions) with no fixed
    grammar this module can safely reduce back to structured conditions --
    a guessed reduction risks being confidently wrong, which is exactly
    the failure mode every other parser in this module refuses to risk.
    The ONLY safe path back to a config is this module's own embedded
    T58_MANUAL_CONFIG_JSON round-trip directive (see module docstring):
    present when the file was generated by `to_python` above (even if
    since hand-edited elsewhere), or added by hand. Raises
    TranslationError when it's absent rather than guess."""
    embedded = _extract_embedded_config(source)
    if embedded is not None:
        return embedded
    raise TranslationError(
        "This Python strategy has no T58_MANUAL_CONFIG_JSON directive, so it can't be safely "
        "reduced back to structured conditions -- arbitrary Python (loops, custom indicators, "
        "hand-written pandas expressions) has no generalizable equivalent in PineScript/MQL5's "
        "condition-comparison syntax, and a guessed translation risks being confidently wrong "
        "rather than just incomplete. Only a Python file this translator generated (or one you've "
        "manually annotated with the same directive) can be translated onward -- translate from "
        "the original PineScript, MQL5, or Manual Strategy Builder config instead."
    )


# ---------------------------------------------------------------------------
# Universal dispatcher -- every source/target combination goes through here
# ---------------------------------------------------------------------------

SUPPORTED_LANGUAGES = ("manual", "pinescript", "mql5", "python")
_TARGET_RENDERERS = {"pinescript": to_pinescript, "mql5": to_mql5, "python": to_python}
_SOURCE_PARSERS = {"pinescript": parse_pinescript, "mql5": parse_mql5, "python": parse_python}


def translate_strategy(source_type: str, source, target_type: str) -> str:
    """Universal entry point covering every direction this module
    supports: manual/pinescript/mql5/python -> pinescript/mql5/python
    (any source language to any OTHER target language). `source` is a
    dict (an already-loaded Manual Strategy Builder config) or a JSON
    string when source_type == "manual"; a raw source-code string for
    every other source_type. Raises TranslationError -- naming exactly
    what's unsupported -- for an unknown language, translating a language
    to itself, or any construct outside the source's supported subset."""
    source_type = (source_type or "").strip().lower()
    target_type = (target_type or "").strip().lower()

    if target_type not in _TARGET_RENDERERS:
        raise TranslationError(
            f"Unsupported translation target '{target_type}'. Expected one of "
            f"{sorted(_TARGET_RENDERERS)}."
        )
    if source_type not in SUPPORTED_LANGUAGES:
        raise TranslationError(
            f"Unsupported translation source '{source_type}'. Expected one of {SUPPORTED_LANGUAGES}."
        )
    if source_type == target_type:
        raise TranslationError(
            f"Source and target are both '{source_type}' -- nothing to translate."
        )

    if source_type == "manual":
        config = source if isinstance(source, dict) else json.loads(source)
    else:
        config = _SOURCE_PARSERS[source_type](source)

    return _TARGET_RENDERERS[target_type](config)
