"""
Limit Order Book + Matching Engine -- a from-scratch model of how a real
exchange's central limit order book (CLOB) actually works: resting limit
orders sit in the book at their price, a new order matches against the
BEST resting price(s) on the opposite side first, and orders at the same
price match in the order they arrived (price-time priority / FIFO).

No external dependencies: price levels are kept in two plain dicts
(price -> FIFO deque of resting orders) plus a sorted list of active
price levels per side, maintained with the stdlib `bisect` module so
"best bid" / "best ask" are always O(1) and inserting/removing a price
level is O(log n) -- the same shape a real matching engine's price-level
index uses, just without the microsecond-latency engineering a live
exchange needs.

Supported order types:
  - LIMIT: rests in the book at its price if it doesn't fully cross the
    spread; any part that DOES cross fills immediately as a trade.
  - MARKET: never rests -- fills immediately against the best available
    opposite-side price(s) until fully filled or the book runs out of
    liquidity, in which case the unfilled remainder is simply dropped
    (a market order has no price to rest at).

Deliberately NOT modeled (real exchanges add all of this, but it's
outside what "here's how the matching engine itself works" needs):
stop orders, iceberg/hidden quantity, post-only/IOC/FOK time-in-force
flags, self-trade prevention, and multi-symbol order routing.
"""
from __future__ import annotations

import bisect
import itertools
from collections import deque
from dataclasses import dataclass, field
from enum import Enum


class Side(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    LIMIT = "limit"
    MARKET = "market"


class OrderBookError(Exception):
    """Raised for invalid order parameters (non-positive price/quantity,
    an order_id that doesn't exist to cancel, etc.)."""


_id_counter = itertools.count(1)


@dataclass
class Order:
    order_id: int
    side: Side
    order_type: OrderType
    price: float | None      # None for market orders
    quantity: float
    remaining: float
    timestamp: int           # monotonically increasing sequence number, NOT wall-clock time


@dataclass
class Trade:
    trade_id: int
    price: float
    quantity: float
    maker_order_id: int      # the RESTING order that was already in the book
    taker_order_id: int      # the INCOMING order that crossed the spread
    timestamp: int


@dataclass
class OrderResult:
    order: Order
    trades: list             # list[Trade] generated by this order
    filled_quantity: float
    remaining_quantity: float
    resting: bool             # True if (part of) this order is now sitting in the book

    @property
    def fully_filled(self) -> bool:
        return self.remaining_quantity <= 1e-12


_trade_id_counter = itertools.count(1)


class LimitOrderBook:
    def __init__(self, symbol: str = "SYMBOL"):
        self.symbol = symbol
        self._seq = itertools.count(1)
        # price -> FIFO deque of resting Orders at that price.
        self._bids: dict[float, deque] = {}
        self._asks: dict[float, deque] = {}
        # Sorted active price levels: bids descending (best first), asks
        # ascending (best first). Kept as plain ascending-sorted lists via
        # bisect; bid "best first" is just "last element" of an ascending
        # list, avoiding a second comparator.
        self._bid_prices: list[float] = []   # ascending; best bid = _bid_prices[-1]
        self._ask_prices: list[float] = []   # ascending; best ask = _ask_prices[0]
        self._orders_by_id: dict[int, Order] = {}
        self.tape: list[Trade] = []          # every trade ever printed, in order

    # ------------------------------------------------------------------
    # Book state
    # ------------------------------------------------------------------
    def best_bid(self) -> float | None:
        return self._bid_prices[-1] if self._bid_prices else None

    def best_ask(self) -> float | None:
        return self._ask_prices[0] if self._ask_prices else None

    def spread(self) -> float | None:
        bid, ask = self.best_bid(), self.best_ask()
        return (ask - bid) if (bid is not None and ask is not None) else None

    def mid_price(self) -> float | None:
        bid, ask = self.best_bid(), self.best_ask()
        if bid is None or ask is None:
            return None
        return (bid + ask) / 2.0

    def depth_snapshot(self, levels: int = 5) -> dict:
        """{'bids': [(price, total_qty), ...] best-first, 'asks': [...] best-first}"""
        bids = [(p, sum(o.remaining for o in self._bids[p])) for p in reversed(self._bid_prices[-levels:])]
        asks = [(p, sum(o.remaining for o in self._asks[p])) for p in self._ask_prices[:levels]]
        return {"bids": bids, "asks": asks}

    # ------------------------------------------------------------------
    # Order entry
    # ------------------------------------------------------------------
    def submit_limit_order(self, side: Side | str, price: float, quantity: float) -> OrderResult:
        side = Side(side)
        if price is None or price <= 0:
            raise OrderBookError("A limit order needs a positive price.")
        if quantity is None or quantity <= 0:
            raise OrderBookError("Order quantity must be positive.")

        order = Order(
            order_id=next(_id_counter), side=side, order_type=OrderType.LIMIT,
            price=float(price), quantity=float(quantity), remaining=float(quantity),
            timestamp=next(self._seq),
        )
        trades = self._match(order)
        resting = False
        if order.remaining > 1e-12:
            self._rest(order)
            resting = True
        return OrderResult(order, trades, order.quantity - order.remaining, order.remaining, resting)

    def submit_market_order(self, side: Side | str, quantity: float) -> OrderResult:
        side = Side(side)
        if quantity is None or quantity <= 0:
            raise OrderBookError("Order quantity must be positive.")

        order = Order(
            order_id=next(_id_counter), side=side, order_type=OrderType.MARKET,
            price=None, quantity=float(quantity), remaining=float(quantity),
            timestamp=next(self._seq),
        )
        trades = self._match(order)
        # A market order never rests -- any unfilled remainder (the book
        # ran out of opposite-side liquidity) is simply dropped.
        return OrderResult(order, trades, order.quantity - order.remaining, order.remaining, resting=False)

    def cancel_order(self, order_id: int) -> bool:
        """Removes a resting order from the book. Returns False (not an
        error) if the order_id doesn't exist or has already fully
        filled/been cancelled -- cancel-of-a-gone-order is a normal race
        in any real exchange, not a bug."""
        order = self._orders_by_id.pop(order_id, None)
        if order is None:
            return False
        book = self._bids if order.side == Side.BUY else self._asks
        prices = self._bid_prices if order.side == Side.BUY else self._ask_prices
        level = book.get(order.price)
        if level is None:
            return False
        try:
            level.remove(order)
        except ValueError:
            return False
        if not level:
            del book[order.price]
            idx = bisect.bisect_left(prices, order.price)
            if idx < len(prices) and prices[idx] == order.price:
                prices.pop(idx)
        return True

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------
    def _rest(self, order: Order) -> None:
        book = self._bids if order.side == Side.BUY else self._asks
        prices = self._bid_prices if order.side == Side.BUY else self._ask_prices
        if order.price not in book:
            book[order.price] = deque()
            bisect.insort(prices, order.price)
        book[order.price].append(order)
        self._orders_by_id[order.order_id] = order

    def _crosses(self, incoming: Order, resting_price: float) -> bool:
        if incoming.order_type == OrderType.MARKET:
            return True
        if incoming.side == Side.BUY:
            return incoming.price >= resting_price
        return incoming.price <= resting_price

    def _match(self, incoming: Order) -> list[Trade]:
        trades: list[Trade] = []
        opposite_book = self._asks if incoming.side == Side.BUY else self._bids
        opposite_prices = self._ask_prices if incoming.side == Side.BUY else self._bid_prices
        # Best-first order: ascending for asks (index 0 first, walk forward),
        # descending for bids (index -1 first, walk backward).
        best_first = iter(opposite_prices) if incoming.side == Side.BUY else reversed(opposite_prices)

        for level_price in list(best_first):
            if incoming.remaining <= 1e-12:
                break
            if not self._crosses(incoming, level_price):
                break  # price levels are sorted, so nothing further can cross either
            level = opposite_book.get(level_price)
            if not level:
                continue
            while level and incoming.remaining > 1e-12:
                resting = level[0]
                fill_qty = min(incoming.remaining, resting.remaining)
                trade = Trade(
                    trade_id=next(_trade_id_counter), price=level_price, quantity=fill_qty,
                    maker_order_id=resting.order_id, taker_order_id=incoming.order_id,
                    timestamp=next(self._seq),
                )
                trades.append(trade)
                self.tape.append(trade)
                incoming.remaining -= fill_qty
                resting.remaining -= fill_qty
                if resting.remaining <= 1e-12:
                    level.popleft()
                    self._orders_by_id.pop(resting.order_id, None)
            if not level:
                del opposite_book[level_price]
                idx = bisect.bisect_left(opposite_prices, level_price)
                if idx < len(opposite_prices) and opposite_prices[idx] == level_price:
                    opposite_prices.pop(idx)

        return trades
